### ISSUE TITLE
Make fixed groups of max values

### ISSUE THREAD

**Issue by ScientiaFelis** [ScientiaFelis/sebmsR#28]
Create a new function that contain groups of set max limits and set the limit based on the max value of the data.

- [x] create values of max limits 
- [x] set maxlimit to a figure based on if max value is within that linimt below a value based on limit size

**Comment by larspett** [comment]
[steps_for_2022_lock_instead_of _dynamic.xlsx](https://github.com/ScientiaFelis/sebmsR/files/13225952/steps_for_2022_lock_instead_of._dynamic.xlsx)

**Comment by larspett** [comment]
It looks good! Some tweaks and additions;
- 3000     500     2900  (new step)
- 300     50     275 (new)
- 30     5     28 (new)
- 800     100     750 (new)
- 12000    2000     11000 (new)
- 14000    2000     13000 (new)
- 4000    500    3750 (new)
- 5000    1000    4500 (new)
- 6000    1000    5500 (new)
- 7000    1000    6500 (new)
- 8000    1000    7500 (new)
- 10000    2000    9000 (new)

**Comment by larspett** [comment]
and:
16000     2000     15000
18000     2000      17000
20000     5000     19000

**Comment by larspett** [comment]
PS använd samma skalor för sebms_abundance_year_compare_plot()

**Comment by ScientiaFelis** [comment]
pushat till github
Testa gärna @larspett

**Comment by larspett** [comment]
- 0 to 3000 should have step 500
- 10000 becomes 1e+04 but should be 10000
- year ranges get the first year but not the range (i.e. 2018:2022 becomes 2018, Brun blåvinge_2018-2022.png etc would be better 


![Image](https://github.com/ScientiaFelis/sebmsR/assets/19598308/11b317b9-573f-43c0-a4fe-5d879b0608d6)



Otherwise looks fine but somehow two folders have been created to at the same time



![Image](https://github.com/ScientiaFelis/sebmsR/assets/19598308/0acae55f-16a2-46f2-9147-740d5873ee65)

**Comment by larspett** [comment]
I suggest we fix this one first

**Comment by ScientiaFelis** [comment]
Ok, I need to:

- [ ] set option to not give scientific numbers
- [ ] check steps (specifically 0-3000 --> 500 steps)
- [ ] rename species agg. If they are the only one (saving a name as Rapsfjäril/Rovfjäril creates a directory Rapsfjäril with Rovsjäril.png in)

**Comment by larspett** [comment]
Ahhh so that’s the reason for the directory!

**Comment by ScientiaFelis** [comment]
@larspett  can you test
Should work now
